config/routes.rb
Chatbot::Application.routes.draw do
  resources :responses
  resources :patterns
  resources :categories do
    post "active", :on=>:member
  end
  
  resources :users, :only=>[:show] do
    get "new_category"
    get "trash_can", :on=>:member
  end
  
  scope :controller=>"home" do
    get :search
    get :get_friends
    get :commands
    get :status
    get :discuss
    get :trash_can
  end
  
  get "sign_in" => "sessions#sign_in"
  get "sign_out" => "sessions#sign_out"
  get "sign_in_callback" => "sessions#sign_in_callback"
  

  root :to => 'home#index'

end

app/views/share/_about_modal.html.haml
.modal.fade#about(style="display:none;")
  .modal-header
    %a.close(data-dismiss="modal") ×
    %h3 關於
  .modal-body
    .row
      .span3
        %h2
          小兜蟲
          %small 自由的噗浪機器人
        :markdown
          繼筆者第一代機器人[賴聖帝君](http://cssula.nba.nctu.edu.tw/index.php/plurkproject/6-uncategorize/30-2011-05-28-11-24-31.html)死後，心血來潮開發了第二代，也就是這隻小兜蟲，命名由來純粹只是因為筆者自號「大兜蟲」。      

          小兜蟲是用 [TJPlurker](http://code.google.com/p/tjplurker) 開發的，且有一個主要特色是可以像 wiki 般讓所有人編輯他的詞庫，除此之外也有一些小工具。
          ### 相關連結
          *   [小兜蟲噗浪頁](http://www.plurk.com/tonyjan)
          *   [小兜蟲指令集](/commands)
          *   [TJPlurker 專案網站](http://code.google.com/p/tjplurker)
      .span2.thumbnail= image_tag "http://avatars.plurk.com/7910597-big4.jpg"
    %hr
    .row
      .span2.thumbnail= image_tag "http://photos-c.ak.fbcdn.net/hphotos-ak-ash4/316140_153693884724732_100002523642079_259452_1647611834_a.jpg"
      .span3
        %h2
          大兜蟲
          %small 最接近男人的神
        :markdown
          一個喜歡把點子實現的專案狂，興趣是鋼琴、程式、追求雙馬尾。
          ### 相關連結
          *   [個人網站](http://tonytonyjan.heroku.com)
          *   [CSsula 創意工坊](http://cssula.nba.nctu.edu.tw)
          *   [交大網路福利社](http://www.nba.nctu.edu.tw)
  .modal-footer
    %a.btn(data-dismiss="modal") Close

app/views/share/_disquz.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'tjchatbot'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/share/_friend_search.html.haml
- placeholder = current_user==@user ? "輸入好友帳號，給他驚喜 XD" : "尋找其他好友"
= text_field_tag :plurk_id, nil, :placeholder=>placeholder, :class=>"input-large search-query"

:javascript
  function visit_user(){
    plurk_id = $('#plurk_id').val();
    if(plurk_id.length>0) window.location = "/users/"+plurk_id;
  }
  
  $('#plurk_id').keypress(function(e){
    if(e.keyCode==13) visit_user();
  });
- if current_user
  :javascript  
    request = $.ajax({
      url: "/get_friends",
      dataType: "json"
    });
  
    request.done(function(msg){
      availableTags = $.map(msg, function(value, key){
        return { label: value.nick_name+' ('+value.full_name+')', value: value.nick_name }
      });
      $("#plurk_id").autocomplete({
        source: availableTags
      });
    });

app/views/share/_plurk_widget.html.erb
<div style="width:270px; height:400px;"><iframe src="http://www.plurk.com/getWidget?uid=7910597&amp;h=400&amp;w=270&amp;u_info=2&amp;bg=cf682f&tl=cae7fd" width="270" frameborder="0" height="400" scrolling="no"></iframe><div style="float: right; padding: 1px;"> <a href="http://plurk.com/" target="_blank" style="font-size: 10px !important; color: #999 !important; border: none; text-decorate: none;" title="Plurk - A Social Journal for your life">Plurk.com</a></div></div>

app/views/share/_topbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "小兜蟲", root_url, :class=>"brand"
      %ul.nav
        = nav_li "主題總攬", categories_path
        = nav_li "指令集", commands_path
        = nav_li "留言板", discuss_path
        = nav_li "垃圾桶", trash_can_path, :class=>"new-feature"
        = nav_li "關於", "#about", "data-toggle"=>"modal"
      = form_tag search_path, :method=>:get, :class=>"navbar-search pull-left" do
        = text_field_tag :q, @q, :placeholder=>"搜尋主題", :required=>true, :class=>"search-query", :value=>@q 
        = hidden_field_tag :p
        = hidden_field_tag :t
      %ul.nav.pull-right
        - unless signed_in?
          = nav_li "用噗浪登入", sign_in_path
        - else
          = nav_li image_tag(current_user.avatar), "javascript:void(0)"
          %li.dropdown
            %a.dropdown-toggle(href="#" data-toggle="dropdown")
              = current_user.info["display_name"]
              %b.caret
            %ul.dropdown-menu
              = nav_li "我的詞庫", user_path(current_user)
              = nav_li "我的垃圾桶", trash_can_user_path(current_user)
              = nav_li "登出", sign_out_path
= render "share/about_modal"