config/routes.rb
Chatbot::Application.routes.draw do
  resources :responses
  resources :patterns
  resources :categories do
    post "active", :on=>:member
  end
  
  resources :users, :only=>[:show] do
    get "new_category"
    get "trash_can", :on=>:member
  end
  
  scope :controller=>"home" do
    get :search
    get :get_friends
    get :commands
    get :status
    get :discuss
    get :trash_can
  end
  
  get "sign_in" => "sessions#sign_in"
  get "sign_out" => "sessions#sign_out"
  get "sign_in_callback" => "sessions#sign_in_callback"
  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
# encoding: utf-8
class HomeController < ApplicationController
  def index
    @recent_created = Category.actived.public.order('created_at desc').first(5)
    @recent_updated = Category.actived.public.where("created_at!=updated_at").order('updated_at desc').first(5)
  end
  
  def search
    if params[:q].present?
      @q = params[:q]
      @t = params[:t] # topic
      @p = params[:p] # pattern
      @categories = Category.search(params).paginate(:page => params[:page], :per_page => 10)
    end
    
    respond_to do |format|
      format.html{
        flash[:error] = "你沒有輸入任何東西！" if params[:q] && params[:q].blank?
        render "categories/index"
      }
      format.json{render :json=>@categories}
    end
  end
  
  def trash_can
    @categories = Category.unactived.public.order("updated_at desc").paginate(:page => params[:page], :per_page => 10)
  end
  
  # For AJAX
  def status
    render :json=>SmallDo.get_own_profile
  end
  
  def get_friends
    if current_user
      response = current_user.tjp.get_completion
      if response["error_text"]
        redirect_to sign_in_path
      else
        render :json=>response
      end
    else
      redirect_to sign_in_path
    end
  end  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/commands.html.haml
.page-header
  %h1 小兜蟲指令大全
.row
  .span8
    .page-header
      %h2
        Google Map
        %small 回傳一個 Google Map 連結
    %pre [小兜蟲|:]{地點}[怎麼走|怎麼去|在哪裡]
    %h3 範例
    %pre 小兜蟲，請問交大怎麼走
    %pre :交大在哪裡
    
    .page-header
      %h2
        新聞
        %small 從聯合新聞網擷取最新消息
    %pre [小兜蟲|:][國內要聞|經濟產業|數位資訊|最新報導|兩岸國際|系內公告]
    %h3 範例
    %pre 小兜蟲 數位資訊
    %pre : 最新報導
    %p 註：系內公告指的是交大資工系內公告^^"
    
    .page-header
      %h2
        Youtube
        %small 回傳在 Youtube 上找到的第一筆搜尋結果
    %pre [小兜蟲|:]我想[聽|看|點]{歌曲}
    %pre [小兜蟲|:]幫我點{歌曲}
    %h3 範例
    %pre 小兜蟲，幫我點交大人
    %pre :我想聽旭陵子
    %p 註：「我」可略
    
    .page-header
      %h2
        歐趴神算
        %small 算算自己或朋友這學期歐啪的機率
    %pre [小兜蟲|:]算算{名字}這學期如何
    %h3 範例
    %pre 小兜蟲，幫我算算大兜這學期如何？
    %pre :算算大兜這學期？
    
    .page-header
      %h2
        擲骰子
        %small 回傳一個 1 到 6 之間的整數
    %pre [小兜蟲|:]擲骰子
    %h3 範例
    %pre 小兜蟲 擲骰子
  .span4
    %h2 小兜蟲檔案
    %table.table.table-bordered.table-striped
      %thead
        %th 屬性
        %th 資料
      %tbody
        %tr
          %td
            %b 噗浪帳號
          %td= link_to "tonyjan", "http://www.plurk.com/tonyjan"
        %tr
          %td
            %b 姓名
          %td 小兜蟲
        %tr
          %td
            %b 職業
          %td 噗浪機器人
        %tr
          %td
            %b 生日
          %td 2011/3/24
        %tr
          %td
            %b 專長
          %td 吃到一半睡著
        %tr
          %td
            %b 興趣
          %td 發呆
    

app/views/home/discuss.html.haml
.page-header
  %h1
    討論版
    %small 意見、問題、天南地北
.row
  .span12
    = render "share/disquz"

app/views/home/index.html.haml
.row
  .span9
    .hero-unit
      %h1
        小兜蟲詞庫系統 
        %small (Beta)
      %br
      %p 自由的噗浪機器人，編輯小兜蟲的回話，讓他越來越聰（ㄅㄞˊ）明（ㄇㄨˋ）！
      %br
      /
        = form_tag "/search", :method=>:get, :class=>"form-search", :style=>"display:inline;" do
          = text_field_tag :q, nil, :placeholder=>"尋找主題 ", :class=>"input-xlarge search-query"
          = submit_tag "搜尋", :class=>"btn"
      .row
        .span3
          %p
            = link_to "瀏覽主題", categories_path, :class=>"btn btn-info btn-large"
            看看別人寫了些什麼
          %p
            = link_to "新增主題", new_category_path, :class=>"btn btn-primary btn-large"
            調教小兜蟲>///<
        .span4
          %p
            = link_to "查閱指令", commands_path, :class=>"btn btn-success btn-large"
            一探小兜蟲的功能
          %p
            = link_to "個人主題", current_user ? user_path(current_user.info["nick_name"]) : sign_in_path, :class=>"btn btn-danger btn-large"
            讓小兜蟲只針對個人回應
          %p
            = render "share/friend_search"
      .row
        .span8
          %p= render "share/facebook_like_button"
  .span3
    %p
      健康狀態：
      %span#status
    = render "share/plurk_widget"
.row
  .span6
    %h2 新主題
    - @recent_created.each do |c|
      .row= render :partial=>"categories/short_category", :object=>c
  .span6
    %h2 近期更新
    - @recent_updated.each do |c|
      .row= render :partial=>"categories/short_category", :object=>c
= render "share/facebook_script"

:javascript
  //$('.coming-soon').tooltip({title:"即將推出", placement:"left"});
  $('.new-feature').tooltip({title:"新玩意", placement:"bottom", trigger:"manual"});
  $('.new-feature').tooltip("show");
:javascript
  request = $.ajax({
    url:"/status",
    dataType: "json",
    beforeSend: function(xhr){
      $('#status').html('<img alt="Loading..." src="/assets/loader.gif" />');
    }
  });

  request.done(function(msg){
    if(msg.error_text){
      $('#status').html('<span class="label label-important">噗浪掛了：'+msg.error_text+'</span>');
    }else{
      $('#status').html('<span class="label label-success">小兜蟲沒問題！</span>');
    }
  });

app/views/home/search.html.haml
.hero-unit
  %h1
    即時預覽
    %small 你發噗，我回噗
  %br
  = form_tag search_path, :method=>:get, :class=>"form-search", :style=>"display:inline;" do
    = text_field_tag :q, nil, :placeholder=>"ex. 早安", :required=>true, :class=>"input-xxlarge search-query", :value=>@q
    = hidden_field_tag :p
    = submit_tag "發噗", :class=>"btn btn-warning btn-large"
    %br
    = label_tag :t, check_box_tag(:t)+"同時搜主題", :class=>"checkbox"
.row
  .span12
    - if @categories.present?
      = render "categories/two_columns_categoryes"
    - elsif params[:q].present?
      .row
        .offset3.span6
          %h2
            恭喜！你挖到小兜蟲尚未被開發的領域！
            = link_to "我要貢獻", new_category_path, :class=>"btn btn-primary btn-large"

app/views/home/trash_can.html.haml
.page-header
  = link_to "我的垃圾桶", trash_can_user_path(current_user), :class=>"btn btn-info btn-large pull-right" if current_user && current_user != @user
  %h1 
    = controller_name == "users" ? "#{@user.info['display_name']}的垃圾桶" : "公共垃圾桶"
    %small 這裡放著所有被刪除的主題，可以透過回復讓小兜蟲重新使用這些主題
= will_paginate @categories, :renderer => BootstrapPagination::Rails
= render "categories/two_columns_categoryes"
= will_paginate @categories, :renderer => BootstrapPagination::Rails