config/routes.rb
Chatbot::Application.routes.draw do
  resources :responses
  resources :patterns
  resources :categories do
    post "active", :on=>:member
  end
  
  resources :users, :only=>[:show] do
    get "new_category"
    get "trash_can", :on=>:member
  end
  
  scope :controller=>"home" do
    get :search
    get :get_friends
    get :commands
    get :status
    get :discuss
    get :trash_can
  end
  
  get "sign_in" => "sessions#sign_in"
  get "sign_out" => "sessions#sign_out"
  get "sign_in_callback" => "sessions#sign_in_callback"
  

  root :to => 'home#index'

end

app/models/category.rb
# encoding: utf-8
class Category < ActiveRecord::Base
  scope :actived, where(:is_active => true)
  scope :unactived, where(:is_active => false)
  scope :public, where(:user_id=>nil)
  
  has_many :patterns, :dependent=>:destroy
  has_many :responses, :dependent=>:destroy
  belongs_to :user
  
  accepts_nested_attributes_for :patterns, :responses, :reject_if=>proc { |attributes| attributes[:content].blank? }, :allow_destroy=>true
  
  validates :name, :presence=>true, :uniqueness=>{:scope=>:user_id}
  validate :pattern_fields_cannot_be_blank, :response_fields_cannot_be_blank
  
  def pattern_fields_cannot_be_blank
    errors.add(:pattern, "fields can't be blank") if self.patterns.blank?
  end
  
  def response_fields_cannot_be_blank
    errors.add(:response, "fields can't be blank") if self.responses.blank?
  end
  
  # Search categories' title
  def self.search_by_title query
    Category.where(["user_id IS NULL AND name LIKE ?", "%#{query}%"])
  end
  
  # Search categories that can accept the query.
  def self.search_by_pattern query
    cats = []
    Category.all.each{|cat|
      cats << cat if cat.public? && cat.match?(query)
    }
    return cats
  end
  
  # opt[:p] for pattern
  # opt[:t] for title
  def self.search opt={}
    ret = []
    ret |= search_by_title(opt[:q]) if opt[:t]
    ret |= search_by_pattern(opt[:q]) if opt[:p]
    return ret
  end
  
  # Check if the given string can be accepted by this category.
  def match? string
    match = false
    patterns.each{|p|
      p string, p, "==="
      if string =~ Regexp.new(p.content)
        match = true
        break
      end
    }
    return match
  end
  
  def public?
    ! user
  end
  
  def private?
    user
  end
  
  def recent_patterns
    patterns.sort_by(&:updated_at).reverse
  end
  
  def recent_responses
    responses.sort_by(&:updated_at).reverse
  end
end

app/controllers/categories_controller.rb
# encoding: utf-8
class CategoriesController < ApplicationController
  before_filter :require_sign_in_if_is_private, :require_friend, :only=>[:create, :edit, :update]
  
  def index
    @categories = Category.actived.public.order("id desc").paginate(:page => params[:page], :per_page => 10)
  end
  
  def new
    @category = Category.new
    
    3.times{
      @category.patterns.build
      @category.responses.build
    }
  end
  
  def create    
    @category ||= Category.new(params[:category])

    # if user signed in, then record his name
    if current_user
      @category.patterns.each{|p| p.last_edit_user_id = current_user.id}
      @category.responses.each{|r| r.last_edit_user_id = current_user.id}
    end
    
    if @category.save
      flash[:success] = "提交成功！"
      redirect_to @category.private? ? user_path(@category.user.nick_name) : categories_path
    else
      flash.now[:error] = "提交失敗！"
      need_patterns = 3 - @category.patterns.size
      need_responses = 3 - @category.responses.size
      need_patterns.times{@category.patterns.build}
      need_responses.times{@category.responses.build}
      render "new"
    end
  end
  
  def edit
    @category ||= Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    @category.attributes = params[:category]
    
    # if user signed in, then record his name
    if current_user
      @category.patterns.each{|p| p.last_edit_user_id = current_user.id if p.changed?}
      @category.responses.each{|r| r.last_edit_user_id = current_user.id if r.changed?}
    end
    
    if @category.save
      flash[:success] = "提交成功！"
      redirect_to @category.user ? user_path(@category.user.nick_name) : categories_path 
    else
      flash.now[:error] = "提交失敗！"
      need_patterns = 3 - @category.patterns.size
      need_responses = 3 - @category.responses.size
      need_patterns.times{@category.patterns.build}
      need_responses.times{@category.responses.build}
      render "edit"
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  
  def active
    @category = Category.find(params[:id])
    @category.update_attribute :is_active, params[:active]
    
    flash[:success] = @category.is_active ? "成功啟用" : "已丟入垃圾桶"
    if @category.public?
      redirect_to @category.is_active ? trash_can_path : categories_path
    else
      redirect_to @category.is_active ? trash_can_user_path(@category.user) : user_path(@category.user)
    end
  end
  
  private
  def require_sign_in_if_is_private
    if params[:id]
      @category ||= Category.find(params[:id])
    elsif params[:category]
      @category ||= Category.new(params[:category])
    end
    
    if @category && @category.private?
      require_sign_in
    end
  end
  
  def require_friend
    if params[:id]
      @category ||= Category.find(params[:id])
    elsif params[:category]
      @category ||= Category.new(params[:category])
    end
    
    if @category.private?
      unless current_user.id==@category.user.id || current_user.is_friend_of(@category.user.plurk_id)
        flash[:error] = "權限不足，他不是你朋友！"
        redirect_to root_url
      end
    end
    
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
.row
  .well
    .span11
      %h2
        = category.name
        = link_to "編輯", edit_category_path(category), :class=>"btn btn-info"
        = link_to "刪除", category, :method=>:delete, :class=>"btn btn-danger", :confirm=>"你知道你在做什麼？"
      .row
        .span5
          %h3 表達式
          %ol
            - category.patterns.each do |p|
              %li= p.content
        .span6
          %h3 回答
          %ol
            - category.responses.each do |p|
              %li= p.content

app/views/categories/_form.html.haml
- unless @category.errors.empty?
  .alert.alert-error
    %ul
      - @category.errors.full_messages.each do |msg|
        %li= msg
= form_for @category do |f|
  = f.hidden_field(:user_id) if action_name == "new_category"
  .row
    .span8
      .well
        %h2 溫馨提醒
        :markdown
          *   新增主題之前，建議先搜尋主題看是否已經有人開過類似意義的主題了，有則沿用，以免重創主題。
          
          *   你所做的更動除非系統當機，否則一分鐘內就會生效。

          *   主題撰寫原則是一個主題只表示一個概念群組，如「早安」、「起床了」、「早上好」可以視為一個群組，無論回答「早安」、「早餐吃了沒」、「又是嶄新的一天」怎麼排列組合都不違背語意邏輯。如果你發現你在同一個主題可能做出不同語意的回答，請考慮是否切成兩個主題。
          
          *   你可以選擇僅輸入一般文字或者使用正規表達式，如果要使用後者，非常建議使用[此網站](http://rubular.com)檢測你的正規表達式是否正確。
      = f.label :name, content_tag(:h2, "標題")
      = f.text_field :name
      %span#check_name
      .row
        .span4
          %h2 聽見（支援正規表達式）
          %ul
            = f.fields_for :patterns do |pattern_form|
              %li
                = pattern_form.text_field :content, :class=>"input-xlarge"
                - if action_name=="edit"
                  = pattern_form.check_box :_destroy, :class=>"checkbox"
            %li
              %span.new-field-btn.label.label-success + 新增
        .span4
          %h2 回答
          %ul
            = f.fields_for :responses do |response_form|
              %li
                = response_form.text_field :content, :class=>"input-xlarge"
                - if action_name=="edit"
                  = response_form.check_box :_destroy
            %li
              %span.new-field-btn.label.label-success + 新增
    .well.span3
      = render "categories/regex_tip"
  = f.button "提交", :class=>"btn btn-large btn-primary"
  - if action_name=="edit"
    = f.button "復原", :type=>"reset" , :class=>"btn btn-large"
    = link_to "重新啟用", active_category_path(@category, :active=>true), :method=>:post, :class=>"btn btn-success btn-large" unless @category.is_active
    = link_to "丟到垃圾桶", active_category_path(@category, :active=>false), :method=>:post, :class=>"btn btn-danger pull-right", :confirm=>"這個按鈕丟掉該主題，被丟到垃圾桶的主題仍可去垃圾桶復原，確定要丟掉？" if @category.is_active

- if action_name=="new"
  :javascript
    // Check title when focusout
    $('#category_name').focusout(function(e){
      console.info(this);
      request = $.ajax({
        url:"/search",
        dataType: "json",
        data:{
          q:this.value,
          t:true
        }
      });
      request.done(function(msg){
        if(msg instanceof Array && msg.length>0){
          $('#check_name').html('發現<span class="badge badge-error">'+msg.length+'</span>筆相似主題');
        }else{
          $('#check_name').html('');
        }
      });
    });

:javascript
  // Tooltips for checkbox
  $('.checkbox').tooltip({placement:"right", title:"刪除"})
  // Disable enter key submission.
  $('form').bind("keypress", function (e) {
      if (e.keyCode == 13) return false;
  });
  // New field button
  $('.new-field-btn').click(function(event){
    li = $(this).closest('ul').find('li:nth-last-of-type(2)').clone();
    // Keep only text field
    li.find(':not(input[type=text])').remove();
    // Set name and value of text input tag
    text_field = li.find('input[type=text]')
    new_name = text_field.attr('name').replace(/\[\d+\]/, "["+event.timeStamp+"]")
    text_field.attr('name', new_name).removeAttr('value');
    
    console.info(li);
    $(this).parent().before(li);
  });
  //s.replace(/\[\d\]/, "["+Date.now()+"]")

app/views/categories/_regex_tip.html.haml
%h2 速查
%dl
  %dt [abc]
  %dd a、b、c 三個字中任一個字
  %dt [^abc]
  %dd 任一個除了 a、b、c 以外的字
  %dt [a-z]
  %dd a 到 z 間任一個字
  %dt [a-zA-Z]
  %dd a 到 z 或 A 到 Z 間任一個字
  %dt ^
  %dd 行首
  %dt $
  %dd 行末
  %dt .
  %dd 一個任何字
  %dt \s
  %dd 一個空白
  %dt \S
  %dd  一個非空白
  %dt \d
  %dd  一個數字
  %dt \D
  %dd  一個非數字
  %dt \w
  %dd  任何文字
  %dt \W
  %dd  任何非文字

app/views/categories/_short_category.html.haml
.span6
  .well(style="overflow:auto;")
    %h2
      = short_category.name
      %small= time_ago_in_words(short_category.updated_at, true)
      /= link_to "刪除", short_category, :method=>:delete, :class=>"btn btn-danger pull-right", :confirm=>"你知道你在做什麼？"
      = link_to "重新啟用", active_category_path(short_category, :active=>true), :method=>:post, :class=>"btn btn-success btn-large" unless short_category.is_active
      = link_to "編輯", edit_category_path(short_category), :class=>"btn btn-large pull-right"
      
      
    - if short_category.user
      =link_to  user_path(short_category.user.info["nick_name"]) do
        %span.label.label-important= short_category.user.info["display_name"] 
    - else
      %span.label.label-success 全域
    .row
      .span2
        %h3 聽見
        %ol
          - short_category.patterns.each do |p|
            %li
              = p.content
              %p
                %small
                  = "#{time_ago_in_words(p.updated_at, true)} ago by"
                  - if p.last_edit_user_id
                    =link_to User.find(p.last_edit_user_id).info["display_name"], user_path(User.find(p.last_edit_user_id).info["nick_name"])
                  - else
                    Anonymous
      .span3
        %h3 回答
        %ol
          - short_category.responses.each do |p|
            %li= p.content
            %p
              %small
                = "#{time_ago_in_words(p.updated_at, true)} ago by"
                - if p.last_edit_user_id
                  =link_to User.find(p.last_edit_user_id).info["display_name"], user_path(User.find(p.last_edit_user_id).info["nick_name"])
                - else
                  Anonymous

app/views/categories/_two_columns_categoryes.html.haml
- @categories.each_slice(2) do |pair|
  .row
    = render :partial=>"categories/short_category", :collection=>pair

app/views/categories/edit.html.haml
.page-header
  %h1
    = @category.name
    - if @category.user
      %small= "#{@category.user.info["display_name"]} 的主題"
.row
  .span12
    = render "form"

app/views/categories/index.html.haml
.page-header
  %h1
    主題總攬
    = link_to "新增主題", new_category_path, :class=>"btn btn-primary btn-large"
    %small= "共#{@categories.size}筆搜尋結果" if action_name=="search"
= will_paginate @categories, :renderer => BootstrapPagination::Rails
= render "categories/two_columns_categoryes"
= will_paginate @categories, :renderer => BootstrapPagination::Rails

/
  :javascript
    function scrollalert(){
      scrolltop=document.body.scrollTop;  
      scrollheight=document.documentElement.scrollHeight;
      clientHeight=document.documentElement.clientHeight;
      scrolloffset=20;
      console.info(scrolltop + clientHeight, scrollheight);
      if(scrolltop + clientHeight == scrollheight){
        
      }
    }
    setInterval(scrollalert, 1500);

app/views/categories/new.html.haml
.page-header
  - if action_name=="new_category"
    %h1
      = "新增 #{@user.info["display_name"]} 的主題"
      %small= "讓小兜蟲只對 #{@user.info["display_name"]} 回應"
  - else
    %h1
      新增全域主題
      %small= "讓小兜蟲對所有看到的噗做回應"
.row
  .span12
    = render "categories/form"